#    This file is part of Oku.
#
#    Oku is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Oku is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with Oku.  If not, see <https://www.gnu.org/licenses/>.
cargo-features = ["strip"]
[package]
name = "oku"
version = "0.1.0"
authors = ["Emil Sayahi <limesayahi@gmail.com>"]
edition = "2021"
exclude = ["/.github/**/*", "/.cargo/**/*", "/branding/**/*", "/rust-toolchain", "/.gitignore", "/.whitesource", "/renovate.json", "/CODE_OF_CONDUCT.md", "/CONTRIBUTING.md", "/LICENSE.md", "/SECURITY.md", "/COPYING", "/NOTICE"]
license = "AGPL-3.0-or-later"
description = "A hive browser written in Rust."
repository = "https://github.com/Dirout/oku"
homepage = "https://github.com/Dirout/oku"
readme = "README.md"
resolver = "1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
cairo-rs = { version = "0.15.10", features = ["png"] }
chrono = { version = "0.4.19", features = ["unstable-locales"] }
cid = "0.8.3"
directories-next = "2.0.0"
futures = "0.3.21"
gdk = { version = "0.4.7", package = "gdk4" }
gdk-pixbuf = { version = "0.15.10" }
gio = { version = "0.15.7" }
glib = { version = "0.15.9" }
gtk = { version = "0.4.7", package = "gtk4", features = ["v4_2"], default-features = false }
ipfs = { git = "https://github.com/rs-ipfs/rust-ipfs.git", rev = "111f116" }
ipfs-api-backend-hyper = { version = "0.3.0", features = ["with-hyper-tls"] }
lazy_static = "1.4.0"
libadwaita = { version = "0.1.1" }
notify-rust = { version = "4.5.6", features = ["images", "z"], default-features = false }
pango = { version = "0.15.10" }
url = "2.2.2"
urlencoding = "2.1.0"
reqwest = { version = "0.11.10", features = ["blocking"] }
tokio = { version = "1.17.0", features = ["full"] }
tokio-stream = "0.1.8"
transmission_rs = "0.8.6"
webkit2gtk = { git = "https://gitlab.gnome.org/JanGernert/webkit2gtk5-rs.git", branch = "newsflash4", package = "webkit2gtk5", features = ["v2_34"] }

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
debug = 0
panic = 'abort'

[package.metadata.deb]
section = "utility"
priority = "optional"
assets = [
    ["target/x86_64-unknown-linux-gnu/release/oku", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/oku/README", "644"],
    ["COPYING", "usr/share/doc/oku/COPYING", "644"],
    ["data/hicolor/**/*", "/usr/share/icons/hicolor/", "644"],
]

[package.metadata.rpm]
package = "oku"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
oku = { path = "/usr/bin/oku" }