#    This file is part of Oku.
#
#    Oku is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Oku is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with Oku.  If not, see <https://www.gnu.org/licenses/>.
[package]
name = "oku"
version = "0.1.0"
authors = ["Emil Sayahi <limesayahi@gmail.com>"]
edition = "2018"
exclude = ["/.github/**/*", "/branding/**/*", "/.gitignore", "/.whitesource", "/renovate.json", "/CODE_OF_CONDUCT.md", "/CONTRIBUTING.md", "/LICENSE.md", "/SECURITY.md", "/COPYING", "/NOTICE", "/src/window.glade"]
license = "AGPL-3.0-or-later"
description = "A hive browser written in Rust."
repository = "https://github.com/MadeByEmil/oku"
homepage = "https://github.com/MadeByEmil/oku"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
bincode = "1.3.2"
cairo-rs = { version = "0.9.1", features = ["png"] }
chrono = { version = "0.4.19", features = ["unstable-locales"] }
cid = "0.6.1"
clap = { version = "3.0.0-beta.2", features = ["yaml", "wrap_help", "suggestions", "color"] }
directories-next = "2.0.0"
futures = "0.3.13"
gdk = "0.13.2"
gdk-pixbuf = "0.9.0"
gio = "0.9.1"
glib = "0.10.3"
gtk = { version = "0.14.0", features = ["v3_24"], default-features = false }
ipfs = "0.2.1"
ipfs-api = { version = "0.11.0", features = ["actix"], default-features = false }
lazy_static = "1.4.0"
notify-rust = { version = "4.3.0", features = ["images", "z"], default-features = false }
pango = "0.9.1"
url = "2.2.1"
urlencoding = "1.1.1"
reqwest = { version = "0.11.1", features = ["blocking"] }
tokio = { version = "0.2", features = ["full"] }
webkit2gtk = { version = "0.11.0", features = ["v2_28"] }

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
debug = 0
panic = 'abort'

[package.metadata.deb]
section = "utility"
priority = "optional"
assets = [
    ["target/x86_64-unknown-linux-gnu/release/oku", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/oku/README", "644"],
    ["COPYING", "usr/share/doc/oku/COPYING", "644"],
    ["data/hicolor/**/*", "/usr/share/icons/hicolor/", "644"],
]

[package.metadata.rpm]
package = "oku"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
oku = { path = "/usr/bin/oku" }
