on: [push]

name: 'Build: GNU + Linux (ARM64)'

jobs:
  linux_aarch64:
    name: GNU + Linux (ARM64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Install GTK development dependencies
        run: |
          sudo apt-get install gtk3.0 gtk2.0 libgtk-3-dev libgtk2.0-dev glib2.0 glade -y
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-unknown-linux-gnu
          default: true
          profile: minimal
          #components: rust-src
      - name: Build Oku
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-gnu
      - name: Prepare Oku for upload
        run: |
          cd ./target/aarch64-unknown-linux-gnu/release/
          chmod +x ./oku
          tar -cvf aarch64-oku.gnu+linux.tar \
          oku
      - name: Upload Oku build artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: aarch64-oku.gnu+linux
          path: ./target/aarch64-unknown-linux-gnu/release/aarch64-oku.gnu+linux.tar
          if-no-files-found: error
