on: [push]

name: 'Build: GNU + Linux (ARM64)'

jobs:
  linux_aarch64:
    name: GNU + Linux (ARM64)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Install development dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq gtk3.0 gtk2.0 libgtk-3-dev libgtk2.0-dev libglib2.0-dev glade libsoup-gnome2.4-dev libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu > /dev/null
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-unknown-linux-gnu
          default: true
          profile: minimal
      - name: Build Oku
        uses: actions-rs/cargo@v1
        with:
          cross: true
          command: build
          args: --release --all-features --target aarch64-unknown-linux-gnu
      - name: Prepare Oku for upload
        run: |
          cd ./target/aarch64-unknown-linux-gnu/release/
          chmod +x ./oku
          tar -cvf aarch64-oku.gnu+linux.tar \
          oku
      - name: Upload Oku build artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: aarch64-oku.gnu+linux
          path: ./target/aarch64-unknown-linux-gnu/release/aarch64-oku.gnu+linux.tar
          if-no-files-found: error
