on: [push]

name: 'Package: Debian GNU + Linux (x86_64)'

jobs:
  deb_x86-64:
    name: Debian GNU + Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Install GTK development dependencies
        run: |
          sudo apt-get install gtk3.0 gtk2.0 libgtk-3-dev libgtk2.0-dev libglib2.0-dev glade libsoup-gnome2.4-dev libwebkit2gtk-4.0-dev -y
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          default: true
          profile: minimal
          #components: rust-src
      - name: Install 'cargo-deb'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb
      - name: Build & package Oku
        uses: actions-rs/cargo@v1
        with:
          command: deb
          args: --separate-debug-symbols -- --all-features --target x86_64-unknown-linux-gnu
      - name: Upload Oku build artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-oku.deb.gnu+linux
          path: ./target/debian/oku_*_amd64.deb
          if-no-files-found: error