on:
  push:
    branches: [master]
  pull_request:
name: 'Package: Flatpak for GNU + Linux (x86_64)'
jobs:
  flatpak-builder:
    name: GNU + Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v2
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-linux-gnu
        default: true
        profile: minimal
    - name: Generate manifest
      run: |
        cargo update
        curl -s https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/master/cargo/flatpak-cargo-generator.py --output flatpak-cargo-generator.py > /dev/null
        pip3 install --upgrade --quiet setuptools
        pip3 install --quiet siphash toml
        python3 ./flatpak-cargo-generator.py ./Cargo.lock -o ./build-aux/cargo-sources.json
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install --assumeyes --noninteractive org.freedesktop.Sdk//20.08 org.freedesktop.Platform//20.08 org.freedesktop.Sdk.Extension.rust-nightly//20.08
    - name: Build & package Oku
      uses: bilelmoussaoui/flatpak-github-actions@v1
      with:
        bundle: "oku.flatpak"
        manifest-path: "build-aux/com.github.madebyemil.oku.json"
