on: [push]

name: 'Build: GNU + Linux (x86_64)'

jobs:
  linux_x86-64:
    name: GNU + Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Install development dependencies
        run: |
          sudo apt-get install -y gtk3.0 gtk2.0 libgtk-3-dev libgtk2.0-dev libglib2.0-dev glade libsoup-gnome2.4-dev libwebkit2gtk-4.0-dev
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          default: true
          profile: minimal
          #components: rust-src
      - name: Build Oku
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target x86_64-unknown-linux-gnu
      - name: Prepare Oku for upload
        run: |
          cd ./target/x86_64-unknown-linux-gnu/release/
          strip -v --strip-all ./oku
          chmod +x ./oku
          tar -cvf x86_64-oku.gnu+linux.tar \
          oku
      - name: Upload Oku build artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-oku.gnu+linux
          path: ./target/x86_64-unknown-linux-gnu/release/x86_64-oku.gnu+linux.tar
          if-no-files-found: error